task :default => :all

task :all => [:classinator, :shaper, :alltime_sightings, :pre_xfiles_sightings]

task :classinator do
    ruby "bigfoot_classinator.rb"
end

task :shaper do
    ruby "ufo_shaper.rb"
end

task :alltime_sightings => [:both_sightings, :bigfoot_sightings, :ufo_sightings]

task :both_sightings do
    ruby "alltime_both.rb"
end

task :bigfoot_sightings do
    ruby "alltime_bigfoot.rb"
end

task :ufo_sightings do
    ruby "alltime_ufo.rb"
end

task :pre_xfiles_sightings => [:both_pre_xfiles, :bigfoot_pre_xfiles, :ufo_pre_xfiles]

task :both_pre_xfiles do
    ruby "pre_xfiles_both.rb"
end

task :bigfoot_pre_xfiles do
    ruby "pre_xfiles_bigfoot.rb"
end

task :ufo_pre_xfiles do
    ruby "pre_xfiles_ufo.rb"
end
